name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 23 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      
    - uses: lowlighter/metrics@latest
      with:
          name : Licencias
          filename: metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes
